[package]
name = "grebedb"
version = "0.2.0"
authors = ["Christopher Foo <chris.foo@gmail.com>"]
edition = "2018"
description = "Lightweight embedded key-value store/database backed by files in a virtual file system interface"
repository = "https://github.com/chfoo/grebedb/"
license = "MPL-2.0"
keywords = ["database", "key-value-store"]
categories = ["database-implementations"]

[features]
default = ["compression", "file_locking", "system"]
compression = ["zstd"]
file_locking = ["fslock"]
system = ["uuid/v4"]

[dependencies]
crc32c = "0.6"
data-encoding = "2.3"
relative-path = "1.3"
rmp-serde = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0"
thiserror = "1.0"
uuid = { version = "0.8", features = ["serde"] }
vfs = "0.5"
zstd = { version = "0.7", optional = true }

[target.'cfg(unix)'.dependencies]
fslock = { version = "0.1", optional = true }

[target.'cfg(windows)'.dependencies]
fslock = { version = "0.1", optional = true }

[dev-dependencies]
anyhow = "1.0"
clap = "2.33"
indexmap = "1.6.2"
paste = "1.0"
rand = "0.8"
rand_xorshift = "0.3"
statrs = "0.13.0"
tempfile = "3.2.0"
